#!/bin/bash
# Copyright (C) 2023 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

docker_images=(
"mongo:4.2.24"
"cybergarage/puzzledb:latest"
)

DATE=$(date '+%Y-%m-%d')
HOSTNAME=$(hostname)

source ./ycsb-setup

for n in {1..1}
do
    DOCKER_IMAGE_NAME=$(echo ${docker_images[$n]} | sed 's/\//-/g;s/:/-/')
    docker run -d -p 27017:27017 --name ${DOCKER_IMAGE_NAME} ${docker_images[$n]}
    sleep 5
    LOG_FILE_NAME="log/mongo-${DATE}-${HOSTNAME}-${DOCKER_IMAGE_NAME}.log"
    YCSB_PARAMS="-s -P ${YCSB_ROOT}/workloads/workloada"
    ${YCSB_ROOT}/bin/ycsb.sh load mongodb ${YCSB_PARAMS} > ${LOG_FILE_NAME}
    ${YCSB_ROOT}/bin/ycsb.sh run  mongodb ${YCSB_PARAMS} >> ${LOG_FILE_NAME}
    CONTAINER_ID=$(docker ps -a --filter "ancestor=${docker_images[$n]}" --format "{{.ID}}")
    docker stop $CONTAINER_ID
    docker rm $CONTAINER_ID
    sleep 5
done
