#!/bin/bash
# Copyright (C) 2023 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PG_CONNECTOR=postgresql-42.6.0.jar
YCSB_DB_PROPERTIES=`pwd`/pb.properties

docker_images=(
"postgres:15.4"
"cybergarage/puzzledb:latest"
)

source ./ycsb-setup

if [ ! -f ${PG_CONNECTOR} ]; then
  wget https://jdbc.postgresql.org/download/${PG_CONNECTOR}
fi

if [ ! -f ${YCSB_JDBC_LIB}/${PG_CONNECTOR} ]; then
  cp ${PG_CONNECTOR} ${YCSB_JDBC_LIB}
fi

for n in {1..1}
do
    DOCKER_IMAGE_NAME=$(echo ${docker_images[$n]} | sed 's/\//-/g;s/:/-/')
    docker run -d -p 27017:27017 --name ${DOCKER_IMAGE_NAME} ${docker_images[$n]}
    sleep 5
    ./pg-setup
    DATE=$(date '+%Y-%m-%d')
    LOG_FILE_NAME="log/mysql-${DATE}-${DOCKER_IMAGE_NAME}.log"
    YCSB_PARAMS="jdbc -s -P ${YCSB_ROOT}/workloads/workloada -P ${YCSB_DB_PROPERTIES}"
    ${YCSB_ROOT}/bin/ycsb.sh load ${YCSB_PARAMS} > ${LOG_FILE_NAME}
    ${YCSB_ROOT}/bin/ycsb.sh run  ${YCSB_PARAMS} >> ${LOG_FILE_NAME}
    CONTAINER_ID=$(docker ps -a --filter "ancestor=${docker_images[$n]}" --format "{{.ID}}")
    docker stop $CONTAINER_ID
    docker rm $CONTAINER_ID
done
