#!/bin/bash
# Copyright (C) 2023 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

docker_images=(
"redis:6.2"
"cybergarage/puzzledb:latest"
)

for n in {0..1}
do
    docker run -d -p 6379:6379 ${docker_images[$n]}
    sleep 5
    BENCH_NAME=$(echo ${docker_images[$n]} | sed 's/\//-/g;s/:/-/')
    DATE=$(date '+%Y-%m-%d')
    LOG_FILE_NAME="log/redis-${DATE}-${BENCH_NAME}.log"
    redis-benchmark -t get,set -n 10000 > ${LOG_FILE_NAME}
    CONTAINER_ID=$(docker ps -a --filter "ancestor=${docker_images[$n]}" --format "{{.ID}}")
    docker stop $CONTAINER_ID
    docker rm $CONTAINER_ID
done
