#!/bin/bash
# Copyright (C) 2025 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TABLES=5
TABLE_SIZE=10000
HOST=localhost

USER=sysbench
DB=sysbench

PGSQL_HOST=${HOST}
PGSQL_PORT=5433
PGPSQL_USER=${USER}
PGSQL_DB=${DB}

CMDS=("prepare" "run")
for CMD in ${CMDS[@]}
do
  sysbench oltp_read_write --db-driver=pgsql --tables=${TABLES} --table-size=${TABLE_SIZE} --pgsql-host=${PGSQL_HOST} --pgsql-port=${PGSQL_PORT} --pgsql-user=${PGPSQL_USER} --pgsql-db=${PGSQL_DB} ${CMD}
done
